fos_user:
    db_driver: orm
    firewall_name: main
    user_class: PiaApi\Entity\Oauth\User
    from_email: 
        address: "accounts@pialab.io"
        sender_name: PiaLab Account Manager
    use_flash_notifications: false
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template:   pia/Email/password_resetting.email.twig