jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'

    handlers:
        datetime:
            default_format: 'Y-m-d\TH:i:sO' #ISO 8601
        array_collection:
            initialize_excluded: false

    default_context:
        serialization:
            serialize_null: true
            groups: ['Default']
            enable_max_depth_checks: true
        deserialization:
            serialize_null: true
            groups: ['Default']
    
    object_constructors:
        doctrine:
            fallback_strategy: "null"

#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
