[template]
src = "env.tmpl"
dest = ".env"
keys = [
    "/url/addr",
    "/symfony/env",
    "/symfony/cors/allow",
    "/client/url",
    "/client/id",
    "/client/secret",
    "/postgres/hostname",
    "/postgres/root/username",
    "/postgres/root/password",
    "/postgres/default/dbname",
    "/postgres/default/username",
    "/postgres/default/password",
    "/smtp/default/url",
    "/smtp/default/mailer",
    "/smtp/default/mailer_name",
]
