[template]
src = "env.tmpl"
dest = ".env"
keys = [
       "/symfony/env",
       "/symfony/cors/allow",
       "/postgres/hostname",
       "/postgres/root/username",
       "/postgres/root/password",
       "/postgres/default/dbname",
       "/postgres/default/username",
       "/postgres/default/password",
       "/smtp/default/url",
]
