fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_oauth_server_token:
    path: /oauth/v2/token
    defaults:
        _controller: PiaApi\Controller\Pia\OauthController:tokenAction
    methods:  [POST]