# fos_oauth_server_token:
#     resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
#     methods:  [GET, POST, OPTIONS]

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting