# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            # Parameters
            $FOSUserResettingRetryTTL: '%fos_user.resetting.retry_ttl%'
            # $SecurityRoleHierarchyRoles: '%security.role_hierarchy.roles%'

            # Services
            FOS\UserBundle\Mailer\MailerInterface: '@fos_user.mailer.twig_swift'
        
    PiaApi\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    PiaApi\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    sensio_framework_extra.view.listener:
        alias: Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener

    PiaApi\Auth\PasswordResettingListener:
        tags:
            - { name: kernel.event_subscriber }

    # Used to fix bug when updating and entity througth REST api
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        public: false