# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: pialab/parameters.yaml }

parameters:
    locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            # Parameters
            $FOSUserResettingRetryTTL: '%fos_user.resetting.retry_ttl%'
            $KernelProjectDir: '%kernel.project_dir%'
            # $SecurityRoleHierarchyRoles: '%security.role_hierarchy.roles%'

            # Services
            FOS\UserBundle\Mailer\MailerInterface: '@fos_user.mailer.twig_swift'
            Nelmio\ApiDocBundle\ApiDocGenerator: '@nelmio_api_doc.generator.default'

    PiaApi\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php,Auth/ClientManager.php}'

    PiaApi\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    sensio_framework_extra.view.listener:
        alias: Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener

    PiaApi\Auth\PasswordResettingListener:
        tags:
            - { name: kernel.event_subscriber }

    PiaApi\Security\Voter\PermissionVoter:
        arguments: ['@security.role_hierarchy']
        tags: [security.voter]
    PiaApi\Security\Voter\CanManageUsersVoter:
        tags: [security.voter]

    PiaApi\Security\Role\RoleHierarchy:
        arguments: ['@security.token_storage', '%security.role_hierarchy.roles%', '@security.role_hierarchy']


    PiaApi\Auth\ClientManager:
        arguments:
            - '@fos_oauth_server.entity_manager'
            - '%fos_oauth_server.model.client.class%'

    FOS\OAuthServerBundle\Model\ClientManagerInterface: '@PiaApi\Auth\ClientManager'

    api_exception_subscriber:
        class: PiaApi\EventListener\ApiExceptionSubscriber
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

    # Used to fix bug when updating and entity througth REST api
    # jms_serializer.object_constructor:
    #     alias: jms_serializer.doctrine_object_constructor
    #     public: false
